### ISSUE TITLE
App Invite dialog: after completion restarts the app.

### ISSUE THREAD

**Issue by umeshbeecavegames** [nodrock/ANE-Facebook#7] opened 2015-07-30 21:24 UTC
After the completion of app invite, the app which started the dialog restarts.

**Comment by umeshbeecavegames** [comment] 2015-07-30 21:54
<img width="695" alt="screen shot 2015-07-30 at 4 53 45 pm" src="https://cloud.githubusercontent.com/assets/12498551/8996162/aa81f526-36db-11e5-9bd0-11b67ea5efaa.png">

**Comment by nodrock** [comment] 2015-08-04 19:27
Hi FBAppCall doesn't exist in FB IOS SDK 4.x so the documentation must be outdated. I will investigate this issue further. Have you exact steps how to reproduce this behaviour?

**Comment by umeshbeecavegames** [comment] 2015-08-04 19:43
Click on app Invite button in your app which you are using to call the appInvite function in ANE.
The dialog which has app invite link and image opens and asks us to input any custom message.
Click next on this dialog.

Then a friend selector dialog comes up and ask us to select friends, and on this dialog there is a "send" button. 
Press send button, sends the request but the app from which this was done, restarts.
It doesnt return to the point where button was clicked.

**Comment by nodrock** [comment] 2015-08-09 21:17
Could you please try this [ANE](http://www.filedropper.com/airfacebook). I fixed one issue with nil and maybe it has also something to do with your problem. Thank you

**Comment by nodrock** [comment] 2015-08-11 11:32
I released version 4.5.0 so please try to use this version and let me know you still encounter this issue. Thank you

**Comment by nodrock** [comment] 2015-09-23 13:53
I was unable to reproduce this issue so I will close it. If anyone finds a way to reproduce it please reopen this ticket. Thank you

**Closed as completed by nodrock** 2015-09-23 13:53 UTC
