### ISSUE TITLE
ios: problem with login / always get canceled

### ISSUE THREAD

**Issue by mymane** [nodrock/ANE-Facebook#4] opened 2015-07-09 15:24 UTC
hey,

I got user canceled back althought I pressed okay. ;(
Thanks for help!
Facebook App is setuped.
App.xml is setup with right "id>", key>CFBundleURLSchemes/key>, key>FacebookAppID/key> ,key>FacebookDisplayName/key> and extensionID>com.freshplanet.AirFacebook/extensionID>

Here is a sum of the code:
import com.freshplanet.ane.AirFacebook.Facebook;

private var _facebook : Facebook;

this._facebook = Facebook.getInstance();
Facebook.logEnabled = true;
Facebook.nativeLogEnabled = true;
this._facebook.init( "AppId" );

this._facebook.logInWithReadPermissions( [ "email" ], this.onSessionOpened );

private function onSessionOpened( bIsSuccess : Boolean, bIsUserCancelled : Boolean, error : String ) : void {
this._facebook.requestWithGraphPath( "me", null, "GET", this.onGraphReturned );
}

[AirFacebook][AS3] FACEBOOK about to call handleOpenURL on args: [] with reason: standard
[AirFacebook][NATIVE] initFacebook
[AirFacebook][NATIVE] Trying to open session with read permissions: email
[AirFacebook][AS3] FACEBOOK about to call handleOpenURL on args: [] with reason: standard
[AirFacebook][NATIVE] Login failed! User cancelled! (Error details : (null) )
[AirFacebook][AS3] No access token!
[AirFacebook][NATIVE] getAccessToken
[AirFacebook][AS3] FACEBOOK about to call handleOpenURL on args: [] with reason: standard
[AirFacebook][NATIVE] Trying to open session with read permissions: email
[AirFacebook][AS3] FACEBOOK about to call handleOpenURL on args: [] with reason: standard
[AirFacebook][NATIVE] Login failed! User cancelled! (Error details : (null) )
[AirFacebook][AS3] No access token!
[AirFacebook][NATIVE] getAccessToken

**Comment by nodrock** [comment] 2015-07-14 08:13
This kind of error are almost always connected to wrong setting of application id. But I will try to investigate it. Thank you for your report. Sorry it took me so long to answer but I was on vacation.

**Comment by mymane** [comment] 2015-07-14 14:59
I checked this double before I wrote that post. Just to clear this out. 

You mean the app-descriptor file, right?

``` javascript
<?xml version="1.0" encoding="utf-8"?>
<application xmlns="http://ns.adobe.com/air/application/17.0">
    <copyright>me</copyright>
    <id>com.nothing.game</id>
```

later I have:

``` javascript
                <key>MinimumOSVersion</key>
                    <string>6.0</string>
                <key>CFBundleURLTypes</key>
                <array>
                    <dict>
                        <key>CFBundleURLSchemes</key>
                            <array>
                                <string>fbMyAppId</string>
                            </array>
                    </dict>
                </array>
                <key>FacebookAppID</key>
                    <string>MyAppId</string>
                <key>FacebookDisplayName</key>
                    <string>AppNameSameAsFacebook</string>
            ]]>
        </InfoAdditions>
        <Entitlements>
            <![CDATA[
```

thx for your help ;)

**Comment by nodrock** [comment] 2015-07-14 15:22
Could you please also check settings in your FB app http://snag.gy/gkRvo.jpg
We now use this ANE on two separate projects and didn't have issue like this after migrate from freshplanet's ANE. Have you used freshplanet's ANE or it's a new project?

**Comment by nodrock** [comment] 2015-07-14 15:24
And one last question. Which AIR SDK do you use?

**Comment by nodrock** [comment] 2015-07-14 15:42
[AirFacebook][NATIVE] Trying to open session with read permissions: email
[AirFacebook][AS3] FACEBOOK about to call handleOpenURL on args: [] with reason: standard
[AirFacebook][NATIVE] Login failed! User cancelled! (Error details : (null) )

Based on these three lines I think there was problem in return from FB app or Safari back to application.
There should be some parameters in args: [].

Do you use FB app or Safari? Could you please try to update FB app to latest version, because there were known issues in older versions.

**Comment by mymane** [comment] 2015-07-14 15:54
I used the freshplanet FacebookAir Ane for a more then a month and then suddently it doesn't work anymore. So I checked first my facebook settings but nothing changed there. I have only a ios version and I used AirSDK17. By the way the ane still works if I set my facebook account at IOS->Settings->Facebook. Via Safari or Facebook-App this is not working.
thx for your help!

**Comment by nodrock** [comment] 2015-07-14 16:06
That is weird because it should not work with this ANE this way. There are some [login behaviours](https://github.com/nodrock/ANE-Facebook/blob/master/actionscript/src/com/freshplanet/ane/AirFacebook/FBLoginBehaviorIOS.as) and the default is NATIVE which will never call SYSTEM_ACCOUNT in fallbacks. You can try to set various login behaviours by Facebook.getInstance().setLoginBehavior(..., ...)

**Comment by mymane** [comment] 2015-07-14 16:19
Yeah, I know. ;(
I will try it again. 

By the way can maybe mobileprovision or p12 break it?
Buildiing and so on working well. Sorry just geussing. ;(

**Comment by mymane** [comment] 2015-07-14 16:21
Can maybe mobileprovision or p12 break it?

**Comment by nodrock** [comment] 2015-07-14 16:26
I don't think so.

Could you try to specify CFBundleURLName?

```
<key>CFBundleURLTypes</key>
<array>
    <dict>
        <key>CFBundleURLName</key>
        <string>com.xxx.xxx</string>
        <key>CFBundleURLSchemes</key>
        <array>
           <string>fbXXXXXXXX</string>
        </array>
    </dict>
</array>
```

**Comment by nodrock** [comment] 2015-07-14 19:19
I recommend you to look at these links https://github.com/ccsoft/cordova-facebook/issues/6 and http://stackoverflow.com/questions/20876208/ios-facebook-sdk-user-cancelled-login-when-running-app-on-device It should by only problem with settings in Facebook. Let me know if you will have any progress. Thank you

**Comment by mymane** [comment] 2015-07-15 09:55
I added CFBundleURLName like it is on facebook and Id on top of the app-descriptor.
I read all links.
I create a testapp.
I noticed that on facebook there is set v2.2, but I don't find a way to change it. (Safari-Url says: https://m.facebook.com/v2.3/dialog/oauth/confirm) 
By the way it always opened this link.
The "old" facebookAir from fp goes to v2.2, but this is also not working anymore (thats the reason for searching a new one).

**Comment by mymane** [comment] 2015-07-15 11:58
So this if I use IOS->Settings->Facebook (Logged In):
[AirFacebook][NATIVE] initFacebook
[AirFacebook][AS3] FACEBOOK about to call handleOpenURL on args: [] with reason: standard
[AirFacebook][NATIVE] Trying to open session with read permissions: email
[AirFacebook][AS3] FACEBOOK about to call handleOpenURL on args: [] with reason: standard
[AirFacebook][NATIVE] Login success! grantedPermissions: {(
    "user_friends",
    "user_birthday",
    email,
    "public_profile",
    "user_location"
)} declinedPermissions: {(
)}
[AirFacebook][AS3] [FBAccessToken appID:'123...123' declinedPermissions:'' expirationDate:'64092211200' permissions:'user_location,user_birthday,email,public_profile,user_friends' refreshDate:'1436961028.28538' tokenString:'CAAXujaz3nRXoQiAk2hNMWhmzbH4zSlTn5G9J6K7FZBD5GfnwZAnpEtKPfuHBeMm5dniHV8L79lXkVKheYnK4JUiV2JYQxEUQ235biZBPkBgiOMSmcvpkhKORiiyeK6S5H9ZBpbkZBeFoqRZCjHgleDNM3ZCyxHZAZCZACjhMIjqYruF7ggdu99QgXHA714duYeS6IBkC8BWuJVNhoIvJtCcPX2dp6h3w9GZAit8KWD5bjpkgIOSTHblmnaYwUW8hED0AZDZD' userID:'123...123']
[AirFacebook][NATIVE] getAccessToken

But If delete this account form settings then it doesn't work anymore.
By the way I only want permission for email.

**Comment by nodrock** [comment] 2015-07-15 12:08
It's ok if you get more permissions. Login always get public_profile permission and if you have ever granted that app any other permission you will get it also. But I don't understand why it works with system account if you didn't set that behaviour. Could you please try to test it with AIR18 only to be sure that there is no problem in that, because AIR17 had a lot of bugs and we never used it in production.

**Comment by mymane** [comment] 2015-07-15 12:13
Yeah, sure I will try 18.

I also tryed some LoginBehaviour.
Facebook.getInstance().setLoginBehavior( FBLoginBehaviorIOS.WEB );
semms to work but the webview is jumping all the time and I have to type in my name/passwort everytime.

**Comment by mymane** [comment] 2015-07-15 12:28
Same with 18 and no setLoginBehaviour:
[AirFacebook][NATIVE] initFacebook
[AirFacebook][AS3] FACEBOOK about to call handleOpenURL on args: [] with reason: standard
[AirFacebook][NATIVE] Trying to open session with read permissions: email
[AirFacebook][AS3] FACEBOOK about to call handleOpenURL on args: [] with reason: standard
[AirFacebook][NATIVE] Login failed! User cancelled! (Error details : (null) )
[AirFacebook][AS3] No access token!
[AirFacebook][NATIVE] getAccessToken

**Comment by nodrock** [comment] 2015-07-15 13:04
So you use _facebook.setLoginBehavior(FBLoginBehaviorIOS.SYSTEM_ACCOUNT); ?
SYSTEM_ACCOUNT is deprecated by Facebook so I don't recommend using it. There are some known issues when it don't work.

**Comment by mymane** [comment] 2015-07-15 13:16
I don't know. First I didn't use it. 

Then I tried NATIVE, SYSTEM_ACCOUNT, BROWSER and WEB.
So which one is the best or right one?

**Comment by nodrock** [comment] 2015-07-15 13:46
Default is NATIVE and it is also recommended by facebook.

**Comment by mymane** [comment] 2015-07-15 15:16
okay. thx.
I also updated my idevice from 7.1.2 to 8.4
Still have "User canceled" ;(

Maybe it's something with deleting my account (ios-settings) or deleting the fb-app.

**Comment by nodrock** [comment] 2015-07-17 07:32
I am unable to reproduce this issue. I tried many many possible options and I always end up with successful login. I am sorry that I cannot provide you with more information. You can always try to build it from soucecodes with some additional logging to find out what's the problem. If you get any new idea let me know.

**Comment by northworks** [comment] 2015-07-17 12:15
thx. good to know.

**Comment by nodrock** [comment] 2015-08-26 07:05
I close this issue until someone else will have the same problem.

**Closed as completed by nodrock** 2015-08-26 07:05 UTC

**Comment by nodrock** [comment] 2015-08-26 15:05
I have found this [link](http://stackoverflow.com/questions/29408299/ios-facebook-sdk-4-0-login-error-code-304). Maybe that could be your issue. Try to call logout before new login.
